export const Users = [
    {
      id:1,
      profilePicture: "profile/person1.jpg",
      username: "vishal sharma",
    },
    {
      id:2,
      profilePicture: "profile/person2.jpg",
      username: "rahul Shrum",
    },
    {
      id:3,
      profilePicture: "profile/person3.jpg",
      username: "fake Durden",
    },
    {
      id:4,
      profilePicture: "profile/person4.jpg",
      username: "natsu Hawks",
    },
    {
      id:5,
      profilePicture: "profile/person5.jpg",
      username: "naruto Holden",
    },
    {
      id:6,
      profilePicture: "profile/person6.jpg",
      username: "tsunade Beauchamp",
    },
    {
      id:7,
      profilePicture: "profile/person7.jpg",
      username: "hinata Bennett",
    },
    {
      id:8,
      profilePicture: "profile/person8.jpg",
      username: "sakura Thomas",
    },
    {
      id:9,
      profilePicture: "profile/person9.jpg",
      username: "bulma Duty",
    },
    {
      id:10,
      profilePicture: "profile/person10.jpg",
      username: "chichi Kocaoglu",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "post/post1.jpg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "post/post2.jpg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "post/post3.jpg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "post/post4.jpg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "post/post5.jpg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "post/post6.jpg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "post/post7.jpg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "post/post8.jpg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "post/post1.jpg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "post/post2.jpg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];